blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions GitHub
    url: https://github.com/flug/my-sofle-v2/discussions
    about: Pour des discussions gÃ©nÃ©rales, idÃ©es, ou questions ouvertes
  - name: ğŸ“š Documentation QMK
    url: https://docs.qmk.fm/
    about: Documentation officielle de QMK Firmware
  - name: ğŸ› ï¸ SplitKB Documentation
    url: https://docs.splitkb.com/hc/en-us/articles/6271110257180-Aurora-Sofle-v2
    about: Documentation du clavier Aurora Sofle v2
